#!/bin/bash

function join_by() {
# join element of array by a given separator
# $1 separator
#
    local IFS="$1"
    shift
    echo "$*"
}

function gmvtag() {
#
# move tag from one commit to another
# $1 tag name
# $2 remote (default origin)
#
	local TAG_NAME=$1
    local REMOTE=$2
    [ -z $REMOTE ] && REMOTE=origin

	if [[ -x $(which git 2> /dev/null) ]]
	then
		git push $REMOTE :refs/tags/$TAG_NAME
		git tag -f $TAG_NAME
		git push $REMOTE master --tags
	else
		echo -e "\n'git' is not installed!"
	fi
}


function getfileline() {
#
# $1 file name
# $2-$3 is the range of file
# $3 is optional if not passed only $2 line is printed
#
    local row
    local content

    [ ! -z "$3" ] && row=$3 || row=$2
    mapfile -s $(($2-1)) -n $(($row-$2+1)) content < "$1"
    printf '%s' "${content[@]}"
}


function countfile() {
#
# $1 source directory (default $HOME)
# $2 file type (extension) (default all)
#
    local BLANK_ESCAPE="s/\ /\\\ /g"

    if [[ ! -z "$1" ]]; then
        local SRC_DIR=$(readlink -f $1)
    else
        local SRC_DIR=$HOME
    fi

    if [[ ! -z "$2" ]]; then
        local FILES=$(find $SRC_DIR -type f | grep "\.$2" | sed "$BLANK_ESCAPE")
    else
        local FILES=$(find $SRC_DIR -type f | sed "$BLANK_ESCAPE")
    fi

    local NUM_FILES=$(echo "$FILES" | wc -l)
    local TOT_SIZE=$(echo "$FILES" | xargs du -ch | tail -n1 | cut -f1)

    echo "file: $NUM_FILES size: $TOT_SIZE"
}


function xzencrypt() {
#
# encrypt with xz
# $1 file name
#
	local IN=$1
	local XZ_OPT="-6e --compress --threads=0"

	if [[ ! -f $IN ]]; then
		echo "$IN is not a regular file"
		exit 1
	fi

	if [[ -x $(which xz) && -x $(which gpg) ]]; then
		tar -c $IN | xz $XZ_OPT | gpg -c > $IN.crypt
	fi
}


function xzdecrypt() {
#
# decrypt with xz
# $1 file name
#
	local IN=$1

	if [[ ! -f $IN ]]; then
		echo "$IN is not a regular file"
		exit 1
	fi

	if [[ -x $(which xz) && -x $(which gpg) ]]; then
		gpg -d $IN | xz --decompress
	fi
}


function randpasswd() {
#
# generate random password
# $1 numbero of char (default 8)
#
	[ -z "$1" ] && local digits=8 || local digits=$1

	local passwd=$(< /dev/urandom tr -dc [:alnum:] | head -c $digits)
	echo -e "\n\t$passwd\n" 
}


function say() {
#
# festival speaks input string
#
	if [[] -x $(which festival 2>/dev/null) ]]
	then
		echo -e "$@" | festival --tts
	else
		echo -e "festival not found"
		exit 0
	fi
}

function typing() {
#
# write file on fly
# $1 filename
#
	if [ -n "$1" ]
	then
		echo -e "write on $1 (Ctrl-D for EOF)"
		tee >> $1
	else
		echo -e "enter a file name"
		exit 1
	fi
}

function vim() {
#
# start vim with nerdtree
#
	if [ -x $(which vim 2>/dev/null) ]
	then
		local STTYOPTS="$(stty --save)"
		stty stop '' -ixoff
		command vim +NERDTreeToggle "$@"
		stty "$STTYOPTS"
	else
		echo -e "vim is not installed"
		exit 0
	fi
}

function calc() {
#
# $1 expression to calculate
#
	echo -e "$1" | bc --mathlib --warn --standard
}

function encode64() {
#
# $@ variable string
#
	echo -e "$@" | base64
}

function decode64() {
#
# $@ variable string
#
	echo -e "$@" | base64 -d
}

function secrm() {
#
# secure remove (shred)
# $@ list of file name
#
	if [ -x $(which shred 2>/dev/null) ]
	then
		shred -xn7 --zero --remove $@ &
	else
		echo -e "shred is not installed"
		exit 0
	fi
}

function swapfilename() {
#
# swap filename
# $1 first file name
# $1 second file name
#
	local TMP=tmp.$$
	mv $1 $TMP
	mv $2 $1
	mv $TMP $2
}

