[Desktop Entry]
Name=mytheme
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Greybird
MetacityTheme=Menta
IconTheme=Fog
GtkColorScheme=fg_color:#3c3c3c3c3c3c,bg_color:#c28fc28fc28f,text_color:#212121212121,base_color:#e666e666e666,selected_fg_color:#f332f332f332,selected_bg_color:#8b4399c4ae14,tooltip_fg_color:#e1e1e1e1e1e1,tooltip_bg_color:#0ccd0ccd0ccd
CursorTheme=mate
CursorSize=24
NotificationTheme=coco
BackgroundImage=/home/christian/Scaricati/images.duckduckgo.com.jpeg
