#!/bin/bash
#
# $1 static library name
# $2 path where library is copied (optional) default current folder
# copy a static library from default library path
#
source ${BASH_LIB}/color.conf


TO=''
LIB=lib$1.a

case $1 in
	-h|--help)
		echo -e "\nTwo arguments required:"
		echo -e "\t1 ${orange}name of static library${reset}"
		echo -e "\t2 ${orange}path where library is copied${reset} (optional)"
		echo -e "\t  if path is void it was copied in the current directory\n"
		exit 0
	;;
fi


[ -z $2 ] && TO="$2" || TO="."


if [[ -d ${LIBRARY_PATH}/${LIB} ]]; then
	echo -e "${green}"
	cp -v ${DEV_LIB_PATH}/${LIB} ${TO}
	echo -e "${reset}"

else
	echo "${LIB} ${red}not found${reset}"
	exit 1
fi

