#!/bin/bash

[ "$1" == "" ] && VERSION=8 || VERSION=$1

JRE_HOME=${JAVA_HOME}/jre
JAVA_HOME=${HOME}/.bin/jdk-1.$VERSION.0
CLASSPATH=${CLASSPATH}:${HOME}/.develop/java/jar
PATH=${JAVA_HOME}/bin:${PATH}


if [[ -d "${JAVA_HOME}" ]]; then
	export JAVA_HOME JRE_HOME CLASSPATH PATH

	echo -e "JAVA_HOME=${JAVA_HOME}"
	echo -e "JRE_HOME=${JRE_HOME}"
	echo -e "CLASSPATH=${CLASSPATH}"
	echo -e "PATH=${PATH}"
	echo
	java -version

else
	echo -e "jdk-1.${VERSION}.0 is not installed!"
fi
