#!/bin/bash
#
# $1 model file
# $2 file name (optionale)
# create $2 file from $1 template
#
# shellcheck source=/dev/null
source "${BASH_LIB}/color.conf"


if [[ "${1}" == "--help" ]]; then
	echo -e "this script required 2 argument:"
	echo -e "\t1 file ${orange}model${reset}"
	echo -e "\t2 file ${orange}name${reset} (optional)"
	exit 0
fi


FILE=""
MODEL=${1}
NAME=${2}
PATH_MODEL=${HOME}/.models

[ -z "${2}" ] && NAME=$1


echo -e "${green}"

for d in $(ls "${PATH_MODEL}"); do
	if [[ -f ${PATH_MODEL}/${d}/${MODEL}.* ]]
	then
		FILE=${NAME}.${MODEL}
		cp -v "${PATH_MODEL}/${d}/${MODEL}".* "${FILE}"
		break
	elif [[ -f ${PATH_MODEL}/${d}/${MODEL} ]]
	then
		FILE=${NAME}
		cp -v "${PATH_MODEL}/${d}/${MODEL}" "${FILE}"
		break
	fi
done

sleep 0.5
echo -e "${reset}"

if [[ -n "${FILE}" ]]; then
	${EDITOR} "${FILE}"
else
	echo -e "template $MODEL does ${red}not exist${reset}!"
	exit 1
fi
