# when leaving the console clear the screen to increase privacy

if [ -f ~/.bash_history ]; then
	rm -iv ~/.bash_history
fi

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi


