
# clear history

history -c
echo -e "\nhistory cleared"
echo -e "bye bye...\n"
sleep 1s

# clear the screen

if [ "$SHLVL" = 1 ]; then
	[ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

