# template makefile
#

BIN_DIR = ~/.bin
FILE_NAME = remove-comment

CC = gcc
OPTION = -Wall -O -std=c11 -pedantic
COMPILE = $(CC) $(OPTION)


compile:
	$(COMPILE) -o $(FILE_NAME) $(FILE_NAME).c

install:
	mv remove-comment $(BIN_DIR)

