" vim configuration file

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
" add others plugin if you want
Plugin 'VundleVim/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'

" All of your Plugins must be added before the following line
call vundle#end()    " required

" airline plugin settings
set laststatus=2
let g:airline#extensions#tabline#enabled=1

" plugin NERDtree 
map <C-n> :NERDTreeToggle <CR>

 
set number
set t_Co=256
set tabstop=4
set shiftwidth=4
set nocompatible

syntax enable
colorscheme desert
filetype plugin indent on

